## Blinkit Data Cleaning and Preparation

 Step 1: Import libraries

In [29]:
import pandas as pd
import numpy as np

Step 2: Load the dataset

In [30]:
df = pd.read_csv("../data/blinkit_dataset.csv")

df.head()

,product_id,product_name,category,brand,price,discount_pct,final_price,rating,num_reviews,delivery_time_min,...,is_organic,packaging_type,weight_g,shelf_life_days,reorder_level,demand_index,date_added,expiry_date,offer_type,delivery_status
0,1,Tata Organic Grocery 300,Grocery,Tata,199.78,25,149.84,4.5,146,37,...,True,Can,750,212,15,73,2023-11-27,2024-06-26,NaN,On-Time
1,2,Mother Dairy Lite Dairy 275,Dairy,Mother Dairy,44.32,30,31.02,4.0,264,36,...,False,Jar,1000,17,24,25,2024-08-07,2024-08-24,NaN,Delayed
2,3,P&G Classic Personal 439,Personal Care,P&G,501.13,0,501.13,3.7,69,17,...,True,Jar,1000,1463,25,100,2024-03-03,2028-03-05,FreeDelivery,On-Time
3,4,Dettol Fresh Household 771,Household,Dettol,627.17,0,627.17,3.9,103,23,...,True,Bottle,200,1143,18,15,2024-08-07,2027-09-24,NaN,On-Time
4,5,Minute Maid Daily Beverages 264,Beverages,Minute Maid,101.69,15,86.44,4.3,422,10,...,True,Can,300,363,30,6,2024-07-04,2025-07-02,NaN,On-Time

Step 3: Understand the dataset

In [31]:
df.shape

(13000, 25)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13000 entries, 0 to 12999
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         13000 non-null  int64
 1   product_name       13000 non-null  object
 2   category           13000 non-null  object
 3   brand              13000 non-null  object
 4   price              13000 non-null  float64
 5   discount_pct       13000 non-null  int64
 6   final_price        13000 non-null  float64
 7   rating             13000 non-null  float64
 8   num_reviews        13000 non-null  int64
 9   delivery_time_min  13000 non-null  int64
 10  city               13000 non-null  object
 11  seller             13000 non-null  object
 12  stock              13000 non-null  int64
 13  sold_quantity      13000 non-null  int64
 14  profit_margin_pct  13000 non-null  float64
 15  is_organic         13000 non-null  bool
 16  packaging_type     13000 non-null  object
 17  weight_g           13000 non-null  int64
 18  shelf_life_days    13000 non-null  int64
 19  reorder_level      13000 non-null  int64
 20  demand_index       13000 non-null  int64
 21  date_added         13000 non-null  object
 22  expiry_date        13000 non-null  object
 23  offer_type         6456 non-null   object
 24  delivery_status    13000 non-null  object
dtypes: bool(1), float64(4), int64(10), object(10)
memory usage: 2.4+ MB

In [33]:
df.describe()

,product_id,price,discount_pct,final_price,rating,num_reviews,delivery_time_min,stock,sold_quantity,profit_margin_pct,weight_g,shelf_life_days,reorder_level,demand_index
count,13000.000000,13000.000000,13000.000000,13000.000000,13000.000000,13000.000000,13000.000000,13000.000000,13000.000000,13000.000000,13000.000000,13000.000000,13000.000000,13000.000000
mean,6500.500000,267.303356,9.959231,240.735212,4.196931,255.000308,27.558769,110.140538,162.400077,22.652708,536.130769,397.555385,21.627769,43.380462
std,3752.921085,199.665148,8.575017,182.405552,0.475863,152.933513,7.139059,19.589137,132.742425,10.088389,406.997451,483.540218,3.928429,27.076935
min,1.000000,10.180000,0.000000,8.140000,2.500000,1.000000,10.000000,52.000000,0.000000,5.000000,100.000000,2.000000,10.000000,0.000000
25%,3250.750000,122.972500,0.000000,108.790000,3.900000,138.000000,23.000000,95.000000,54.000000,13.900000,250.000000,13.000000,19.000000,22.000000
50%,6500.500000,220.240000,10.000000,197.185000,4.200000,219.000000,27.000000,110.000000,120.000000,22.900000,400.000000,231.000000,22.000000,38.000000
75%,9750.250000,350.500000,15.000000,316.882500,4.500000,355.000000,32.000000,125.000000,253.000000,31.400000,750.000000,564.000000,25.000000,63.000000
max,13000.000000,999.930000,30.000000,998.920000,5.000000,1050.000000,56.000000,169.000000,720.000000,40.000000,2000.000000,1825.000000,33.000000,100.000000

Step 4: Check missing values

In [34]:
df.isnull().sum()

product_id              0
product_name            0
category                0
brand                   0
price                   0
discount_pct            0
final_price             0
rating                  0
num_reviews             0
delivery_time_min       0
city                    0
seller                  0
stock                   0
sold_quantity           0
profit_margin_pct       0
is_organic              0
packaging_type          0
weight_g                0
shelf_life_days         0
reorder_level           0
demand_index            0
date_added              0
expiry_date             0
offer_type           6544
delivery_status         0
dtype: int64

In [35]:
df.duplicated().sum()

np.int64(0)

In [36]:
df["offer_type"] = df["offer_type"].fillna("No Offer")

In [37]:
df["offer_type"].isnull().sum()

np.int64(0)

Step 5: Check duplicate records

In [38]:
duplicate_count = df.duplicated().sum()
print("Duplicate Records:", duplicate_count)

Duplicate Records: 0

Step 6: Check incorrect data types

In [39]:
df.dtypes

product_id             int64
product_name          object
category              object
brand                 object
price                float64
discount_pct           int64
final_price          float64
rating               float64
num_reviews            int64
delivery_time_min      int64
city                  object
seller                object
stock                  int64
sold_quantity          int64
profit_margin_pct    float64
is_organic              bool
packaging_type        object
weight_g               int64
shelf_life_days        int64
reorder_level          int64
demand_index           int64
date_added            object
expiry_date           object
offer_type            object
delivery_status       object
dtype: object

In [40]:
df["date_added"] = pd.to_datetime(df["date_added"])
df["expiry_date"] = pd.to_datetime(df["expiry_date"])

In [41]:
df.dtypes

product_id                    int64
product_name                 object
category                     object
brand                        object
price                       float64
discount_pct                  int64
final_price                 float64
rating                      float64
num_reviews                   int64
delivery_time_min             int64
city                         object
seller                       object
stock                         int64
sold_quantity                 int64
profit_margin_pct           float64
is_organic                     bool
packaging_type               object
weight_g                      int64
shelf_life_days               int64
reorder_level                 int64
demand_index                  int64
date_added           datetime64[ns]
expiry_date          datetime64[ns]
offer_type                   object
delivery_status              object
dtype: object

Step 7: Check inconsistent categorical values

In [42]:
print(df["category"].unique())
print(df["brand"].unique())
print(df["city"].unique())
print(df["seller"].unique())
print(df["packaging_type"].unique())
print(df["offer_type"].unique())
print(df["delivery_status"].unique())

['Grocery' 'Dairy' 'Personal Care' 'Household' 'Beverages' 'Snacks'
 'Bakery' 'Fruits & Vegetables']
['Tata' 'Mother Dairy' 'P&G' 'Dettol' 'Minute Maid' 'Britannia'
 'Surf Excel' 'Aashirvaad' 'Harpic' 'Lizol' 'ITC' 'Patanjali' 'Aavin'
 "Lay's" 'Fortune' 'Modern' 'Amul' 'FreshFarm' 'Nivea' 'DailyGreens'
 'Gowardhan' 'Parle' 'BakeHouse' 'Coca-Cola' 'Pepsi' 'Dove' 'Tropicana'
 'Himalaya']
['Bengaluru' 'Jaipur' 'Chennai' 'Delhi' 'Pune' 'Lucknow' 'Mumbai'
 'Kolkata' 'Ahmedabad' 'Hyderabad']
['UrbanSeller' 'QuickStores' 'LocalMart' 'SellerA' 'SellerB' 'DailyNeeds']
['Can' 'Jar' 'Bottle' 'Packet' 'Pouch' 'Box']
['No Offer' 'FreeDelivery' 'FlatDiscount' 'Buy1Get1' 'Cashback']
['On-Time' 'Delayed']

In [43]:
df["category"].value_counts()

category
Bakery                 1713
Grocery                1700
Dairy                  1662
Personal Care          1620
Snacks                 1596
Fruits & Vegetables    1588
Beverages              1561
Household              1560
Name: count, dtype: int64

Step 8: Remove unnecessary spaces

In [44]:
text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    df[col] = df[col].str.strip()

Step 9: Check numerical values

In [45]:
df["rating"].min(), df["rating"].max()

(2.5, 5.0)

In [46]:
df["discount_pct"].min(), df["discount_pct"].max()

(0, 30)

In [47]:
df["price"].min(), df["price"].max()

(10.18, 999.93)

Step 10: Check logical consistency

In [48]:
calculated_price = (
    df["price"] * (1 - df["discount_pct"] / 100)
).round(2)

In [49]:
df["price_check"] = calculated_price == df["final_price"]

df["price_check"].value_counts()

price_check
True     12754
False      246
Name: count, dtype: int64

Step 11: Check dates

In [50]:
invalid_dates = (df["expiry_date"] < df["date_added"]).sum()
print("Invalid expiry dates:", invalid_dates)

Invalid expiry dates: 0

Step 12: Remove the temporary checking column

In [51]:
df.drop(columns=["price_check"], inplace=True)

Step 13: Final validation

In [52]:
print("Dataset Shape:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Records:")
print(df.duplicated().sum())

print("\nData Types:")
print(df.dtypes)

Dataset Shape: (13000, 25)

Missing Values:
product_id           0
product_name         0
category             0
brand                0
price                0
discount_pct         0
final_price          0
rating               0
num_reviews          0
delivery_time_min    0
city                 0
seller               0
stock                0
sold_quantity        0
profit_margin_pct    0
is_organic           0
packaging_type       0
weight_g             0
shelf_life_days      0
reorder_level        0
demand_index         0
date_added           0
expiry_date          0
offer_type           0
delivery_status      0
dtype: int64

Duplicate Records:
0

Data Types:
product_id                    int64
product_name                 object
category                     object
brand                        object
price                       float64
discount_pct                  int64
final_price                 float64
rating                      float64
num_reviews                   int64
delivery_time_min             int64
city                         object
seller                       object
stock                         int64
sold_quantity                 int64
profit_margin_pct           float64
is_organic                     bool
packaging_type               object
weight_g                      int64
shelf_life_days               int64
reorder_level                 int64
demand_index                  int64
date_added           datetime64[ns]
expiry_date          datetime64[ns]
offer_type                   object
delivery_status              object
dtype: object

Step 14: Save cleaned dataset

In [53]:
df.to_csv("../data/Blinkit_Cleaned_Data.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.